// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260211153637_initial_create")]
    partial class initial_create
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Data.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("full_name");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Role" }, "ix_users_role");

                    b.HasIndex(new[] { "Status" }, "ix_users_status");

                    b.HasIndex(new[] { "Email" }, "ux_users_email")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("Data.Models.Condition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BodyRegion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("body_region");

                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "BodyRegion" }, "ix_conditions_body_region");

                    b.HasIndex(new[] { "Code" }, "ix_conditions_code");

                    b.HasIndex(new[] { "Title" }, "ix_conditions_title");

                    b.ToTable("conditions");
                });

            modelBuilder.Entity("Data.Models.ConditionTestRecommendation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConditionId")
                        .HasColumnType("integer")
                        .HasColumnName("condition_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("RecommendedStageCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("recommended_stage_code");

                    b.Property<int>("TestDefinitionId")
                        .HasColumnType("integer")
                        .HasColumnName("test_definition_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ConditionId" }, "ix_ctr_condition_id");

                    b.HasIndex(new[] { "ConditionId", "Priority" }, "ix_ctr_condition_priority");

                    b.HasIndex(new[] { "TestDefinitionId" }, "ix_ctr_test_definition_id");

                    b.HasIndex(new[] { "ConditionId", "TestDefinitionId" }, "ux_ctr_condition_test")
                        .IsUnique();

                    b.ToTable("condition_test_recommendations");
                });

            modelBuilder.Entity("Data.Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BodyRegion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("body_region");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("ParamsSchemaJson")
                        .HasColumnType("text")
                        .HasColumnName("params_schema_json")
                        .HasComment("JSON Schema for exercise parameters");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("visibility");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "BodyRegion" }, "ix_exercises_body_region");

                    b.HasIndex(new[] { "OwnerId" }, "ix_exercises_owner_user_id");

                    b.HasIndex(new[] { "Title" }, "ix_exercises_title");

                    b.HasIndex(new[] { "Visibility" }, "ix_exercises_visibility");

                    b.ToTable("exercises");
                });

            modelBuilder.Entity("Data.Models.ExerciseLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Completed")
                        .HasColumnType("boolean")
                        .HasColumnName("completed");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("MetricsJson")
                        .HasColumnType("text")
                        .HasColumnName("metrics_json")
                        .HasComment("JSON: detailed metrics");

                    b.Property<int?>("PainInt")
                        .HasColumnType("integer")
                        .HasColumnName("pain_int");

                    b.Property<string>("PatientComment")
                        .HasColumnType("text")
                        .HasColumnName("patient_comment");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("patient_id");

                    b.Property<DateTime?>("PerformedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("performed_at");

                    b.Property<decimal?>("RomValue")
                        .HasColumnType("numeric")
                        .HasColumnName("rom_value");

                    b.Property<int>("WorkoutExerciseId")
                        .HasColumnType("integer")
                        .HasColumnName("workout_exercise_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Completed" }, "ix_exercise_logs_completed");

                    b.HasIndex(new[] { "CreatedByUserId" }, "ix_exercise_logs_created_by_user_id");

                    b.HasIndex(new[] { "WorkoutExerciseId", "PerformedAt" }, "ix_exercise_logs_exercise_performed_at");

                    b.HasIndex(new[] { "PatientId" }, "ix_exercise_logs_patient_id");

                    b.HasIndex(new[] { "PatientId", "PerformedAt" }, "ix_exercise_logs_patient_performed_at");

                    b.HasIndex(new[] { "WorkoutExerciseId" }, "ix_exercise_logs_workout_exercise_id");

                    b.ToTable("exercise_logs");
                });

            modelBuilder.Entity("Data.Models.ExerciseLogMedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("ExerciseLogId")
                        .HasColumnType("integer")
                        .HasColumnName("exercise_log_id");

                    b.Property<int>("MediaAssetId")
                        .HasColumnType("integer")
                        .HasColumnName("media_asset_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ExerciseLogId" }, "ix_exercise_log_media_exercise_log_id");

                    b.HasIndex(new[] { "MediaAssetId" }, "ix_exercise_log_media_media_asset_id");

                    b.HasIndex(new[] { "ExerciseLogId", "MediaAssetId" }, "ux_exercise_log_media_log_media")
                        .IsUnique();

                    b.ToTable("exercise_log_media");
                });

            modelBuilder.Entity("Data.Models.ExerciseMedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("integer")
                        .HasColumnName("exercise_id");

                    b.Property<int>("MediaAssetId")
                        .HasColumnType("integer")
                        .HasColumnName("media_asset_id");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("purpose");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ExerciseId" }, "ix_exercise_media_exercise_id");

                    b.HasIndex(new[] { "MediaAssetId" }, "ix_exercise_media_media_asset_id");

                    b.HasIndex(new[] { "ExerciseId", "MediaAssetId" }, "ux_exercise_media_exercise_media")
                        .IsUnique();

                    b.ToTable("exercise_media");
                });

            modelBuilder.Entity("Data.Models.MediaAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("kind");

                    b.Property<int?>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("patient_id");

                    b.Property<Guid?>("UploadedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_user_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "PatientId" }, "ix_media_assets_patient_id");

                    b.HasIndex(new[] { "UploadedByUserId" }, "ix_media_assets_uploaded_by_user_id");

                    b.ToTable("media_assets");
                });

            modelBuilder.Entity("Data.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("full_name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Sex")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("sex");

                    b.Property<string>("TagsJson")
                        .HasColumnType("text")
                        .HasColumnName("tags_json")
                        .HasComment("JSON: custom tags/metadata");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "FullName" }, "ix_patients_full_name");

                    b.HasIndex(new[] { "UserId" }, "ux_patients_user_id")
                        .IsUnique();

                    b.ToTable("patients");
                });

            modelBuilder.Entity("Data.Models.PatientAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("patient_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "PatientId" }, "ix_patient_assignments_patient_id");

                    b.HasIndex(new[] { "UserId" }, "ix_patient_assignments_user_id");

                    b.HasIndex(new[] { "PatientId", "UserId" }, "ux_patient_assignments_patient_user")
                        .IsUnique();

                    b.ToTable("patient_assignments");
                });

            modelBuilder.Entity("Data.Models.PatientCondition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConditionId")
                        .HasColumnType("integer")
                        .HasColumnName("condition_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateOnly?>("OnsetDate")
                        .HasColumnType("date")
                        .HasColumnName("onset_date");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("patient_id");

                    b.Property<string>("Side")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("side");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ConditionId" }, "ix_patient_conditions_condition_id");

                    b.HasIndex(new[] { "CreatedByUserId" }, "ix_patient_conditions_created_by_user_id");

                    b.HasIndex(new[] { "PatientId" }, "ix_patient_conditions_patient_id");

                    b.HasIndex(new[] { "PatientId", "Status" }, "ix_patient_conditions_patient_status");

                    b.ToTable("patient_conditions");
                });

            modelBuilder.Entity("Data.Models.PatientStageStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<Guid>("ChangedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentStageId")
                        .HasColumnType("integer")
                        .HasColumnName("current_stage_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("PatientConditionId")
                        .HasColumnType("integer")
                        .HasColumnName("patient_condition_id");

                    b.Property<int>("ProtocolId")
                        .HasColumnType("integer")
                        .HasColumnName("protocol_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ChangedByUserId" }, "ix_patient_stage_status_changed_by_user_id");

                    b.HasIndex(new[] { "CurrentStageId" }, "ix_patient_stage_status_current_stage_id");

                    b.HasIndex(new[] { "PatientConditionId" }, "ix_patient_stage_status_patient_condition_id");

                    b.HasIndex(new[] { "PatientConditionId", "Status" }, "ix_patient_stage_status_patient_condition_status");

                    b.HasIndex(new[] { "ProtocolId" }, "ix_patient_stage_status_protocol_id");

                    b.ToTable("patient_stage_status");
                });

            modelBuilder.Entity("Data.Models.ProgressEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("PainJson")
                        .HasColumnType("text")
                        .HasColumnName("pain_json")
                        .HasComment("JSON: pain assessment per region");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("patient_id");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<string>("RomJson")
                        .HasColumnType("text")
                        .HasColumnName("rom_json")
                        .HasComment("JSON: ROM measurements");

                    b.Property<int?>("WorkoutSessionId")
                        .HasColumnType("integer")
                        .HasColumnName("workout_session_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CreatedByUserId" }, "ix_progress_entries_created_by_user_id");

                    b.HasIndex(new[] { "PatientId" }, "ix_progress_entries_patient_id");

                    b.HasIndex(new[] { "PatientId", "RecordedAt" }, "ix_progress_entries_patient_recorded_at");

                    b.HasIndex(new[] { "WorkoutSessionId" }, "ix_progress_entries_workout_session_id");

                    b.ToTable("progress_entries");
                });

            modelBuilder.Entity("Data.Models.RehabProtocol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConditionId")
                        .HasColumnType("integer")
                        .HasColumnName("condition_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("visibility");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ConditionId" }, "ix_rehab_protocols_condition_id");

                    b.HasIndex(new[] { "OwnerId" }, "ix_rehab_protocols_owner_user_id");

                    b.HasIndex(new[] { "Visibility" }, "ix_rehab_protocols_visibility");

                    b.ToTable("rehab_protocols");
                });

            modelBuilder.Entity("Data.Models.RehabStage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Goals")
                        .HasColumnType("text")
                        .HasColumnName("goals");

                    b.Property<int>("ProtocolId")
                        .HasColumnType("integer")
                        .HasColumnName("protocol_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ProtocolId" }, "ix_rehab_stages_protocol_id");

                    b.HasIndex(new[] { "ProtocolId", "SortOrder" }, "ix_rehab_stages_protocol_sort");

                    b.HasIndex(new[] { "ProtocolId", "Code" }, "ux_rehab_stages_protocol_code")
                        .IsUnique();

                    b.ToTable("rehab_stages");
                });

            modelBuilder.Entity("Data.Models.StageCriterion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CriteriaJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("criteria_json")
                        .HasComment("JSON: rule definitions (pain/rom/tests)");

                    b.Property<int>("StageId")
                        .HasColumnType("integer")
                        .HasColumnName("stage_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "StageId" }, "ix_stage_criteria_stage_id");

                    b.ToTable("stage_criteria");
                });

            modelBuilder.Entity("Data.Models.Template", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("visibility");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "OwnerId" }, "ix_templates_owner_user_id");

                    b.HasIndex(new[] { "Visibility" }, "ix_templates_visibility");

                    b.ToTable("templates");
                });

            modelBuilder.Entity("Data.Models.TemplateItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomExerciseTitle")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("custom_exercise_title");

                    b.Property<int?>("ExerciseId")
                        .HasColumnType("integer")
                        .HasColumnName("exercise_id");

                    b.Property<string>("ParamsJson")
                        .HasColumnType("text")
                        .HasColumnName("params_json")
                        .HasComment("JSON: instance-specific parameters");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<int>("TemplateId")
                        .HasColumnType("integer")
                        .HasColumnName("template_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ExerciseId" }, "ix_template_items_exercise_id");

                    b.HasIndex(new[] { "TemplateId" }, "ix_template_items_template_id");

                    b.HasIndex(new[] { "TemplateId", "SortOrder" }, "ix_template_items_template_sort");

                    b.ToTable("template_items");
                });

            modelBuilder.Entity("Data.Models.TestDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Instruction")
                        .HasColumnType("text")
                        .HasColumnName("instruction");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("ResultSchemaJson")
                        .HasColumnType("text")
                        .HasColumnName("result_schema_json")
                        .HasComment("JSON Schema for validation");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("visibility");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "OwnerId" }, "ix_test_definitions_owner_user_id");

                    b.HasIndex(new[] { "Title" }, "ix_test_definitions_title");

                    b.HasIndex(new[] { "Visibility" }, "ix_test_definitions_visibility");

                    b.ToTable("test_definitions");
                });

            modelBuilder.Entity("Data.Models.TestResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int?>("PatientConditionId")
                        .HasColumnType("integer")
                        .HasColumnName("patient_condition_id");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("patient_id");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("performed_at");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("result_json")
                        .HasComment("JSON: structured test result");

                    b.Property<decimal?>("ScoreNumeric")
                        .HasColumnType("numeric")
                        .HasColumnName("score_numeric");

                    b.Property<int>("TestDefinitionId")
                        .HasColumnType("integer")
                        .HasColumnName("test_definition_id");

                    b.Property<int?>("WorkoutSessionId")
                        .HasColumnType("integer")
                        .HasColumnName("workout_session_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CreatedByUserId" }, "ix_test_results_created_by_user_id");

                    b.HasIndex(new[] { "PatientConditionId" }, "ix_test_results_patient_condition_id");

                    b.HasIndex(new[] { "PatientId" }, "ix_test_results_patient_id");

                    b.HasIndex(new[] { "PatientId", "PerformedAt" }, "ix_test_results_patient_performed_at");

                    b.HasIndex(new[] { "TestDefinitionId" }, "ix_test_results_test_definition_id");

                    b.HasIndex(new[] { "WorkoutSessionId" }, "ix_test_results_workout_session_id");

                    b.ToTable("test_results");
                });

            modelBuilder.Entity("Data.Models.VisitNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Assessment")
                        .HasColumnType("text")
                        .HasColumnName("assessment");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DiagnosisText")
                        .HasColumnType("text")
                        .HasColumnName("diagnosis_text");

                    b.Property<string>("ExtraJson")
                        .HasColumnType("text")
                        .HasColumnName("extra_json")
                        .HasComment("JSON: additional structured data");

                    b.Property<string>("Objective")
                        .HasColumnType("text")
                        .HasColumnName("objective");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("patient_id");

                    b.Property<string>("Plan")
                        .HasColumnType("text")
                        .HasColumnName("plan");

                    b.Property<string>("Subjective")
                        .HasColumnType("text")
                        .HasColumnName("subjective");

                    b.Property<DateOnly>("VisitDate")
                        .HasColumnType("date")
                        .HasColumnName("visit_date");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "AuthorUserId" }, "ix_visit_notes_author_user_id");

                    b.HasIndex(new[] { "PatientId", "VisitDate" }, "ix_visit_notes_patient_date");

                    b.HasIndex(new[] { "PatientId" }, "ix_visit_notes_patient_id");

                    b.ToTable("visit_notes");
                });

            modelBuilder.Entity("Data.Models.WorkoutExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomExerciseTitle")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("custom_exercise_title");

                    b.Property<int?>("ExerciseId")
                        .HasColumnType("integer")
                        .HasColumnName("exercise_id");

                    b.Property<int?>("InstructionMediaId")
                        .HasColumnType("integer")
                        .HasColumnName("instruction_media_id");

                    b.Property<string>("ParamsJson")
                        .HasColumnType("text")
                        .HasColumnName("params_json")
                        .HasComment("JSON: runtime parameters");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<int>("WorkoutSessionId")
                        .HasColumnType("integer")
                        .HasColumnName("workout_session_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ExerciseId" }, "ix_workout_exercises_exercise_id");

                    b.HasIndex(new[] { "InstructionMediaId" }, "ix_workout_exercises_instruction_media_id");

                    b.HasIndex(new[] { "WorkoutSessionId", "SortOrder" }, "ix_workout_exercises_session_sort");

                    b.HasIndex(new[] { "WorkoutSessionId" }, "ix_workout_exercises_workout_session_id");

                    b.ToTable("workout_exercises");
                });

            modelBuilder.Entity("Data.Models.WorkoutPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("patient_id");

                    b.Property<int?>("SourceTemplateId")
                        .HasColumnType("integer")
                        .HasColumnName("source_template_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CreatedByUserId" }, "ix_workout_plans_created_by_user_id");

                    b.HasIndex(new[] { "PatientId" }, "ix_workout_plans_patient_id");

                    b.HasIndex(new[] { "SourceTemplateId" }, "ix_workout_plans_source_template_id");

                    b.HasIndex(new[] { "Status" }, "ix_workout_plans_status");

                    b.ToTable("workout_plans");
                });

            modelBuilder.Entity("Data.Models.WorkoutSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("patient_id");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<int?>("WorkoutPlanId")
                        .HasColumnType("integer")
                        .HasColumnName("workout_plan_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "PatientId" }, "ix_workout_sessions_patient_id");

                    b.HasIndex(new[] { "PatientId", "ScheduledAt" }, "ix_workout_sessions_patient_scheduled_at");

                    b.HasIndex(new[] { "Status" }, "ix_workout_sessions_status");

                    b.HasIndex(new[] { "WorkoutPlanId" }, "ix_workout_sessions_workout_plan_id");

                    b.ToTable("workout_sessions");
                });

            modelBuilder.Entity("Data.Models.ConditionTestRecommendation", b =>
                {
                    b.HasOne("Data.Models.Condition", "Condition")
                        .WithMany("TestRecommendations")
                        .HasForeignKey("ConditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.TestDefinition", "TestDefinition")
                        .WithMany("Recommendations")
                        .HasForeignKey("TestDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Condition");

                    b.Navigation("TestDefinition");
                });

            modelBuilder.Entity("Data.Models.Exercise", b =>
                {
                    b.HasOne("Data.Identity.User", "Owner")
                        .WithMany("Exercises")
                        .HasForeignKey("OwnerId");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Data.Models.ExerciseLog", b =>
                {
                    b.HasOne("Data.Identity.User", "CreatedBy")
                        .WithMany("ExerciseLogs")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.Patient", "Patient")
                        .WithMany("ExerciseLogs")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.WorkoutExercise", "WorkoutExercise")
                        .WithMany("Logs")
                        .HasForeignKey("WorkoutExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Patient");

                    b.Navigation("WorkoutExercise");
                });

            modelBuilder.Entity("Data.Models.ExerciseLogMedia", b =>
                {
                    b.HasOne("Data.Models.ExerciseLog", "ExerciseLog")
                        .WithMany("Media")
                        .HasForeignKey("ExerciseLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.MediaAsset", "MediaAsset")
                        .WithMany("ExerciseLogMedia")
                        .HasForeignKey("MediaAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExerciseLog");

                    b.Navigation("MediaAsset");
                });

            modelBuilder.Entity("Data.Models.ExerciseMedia", b =>
                {
                    b.HasOne("Data.Models.Exercise", "Exercise")
                        .WithMany("ExerciseMedia")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.MediaAsset", "MediaAsset")
                        .WithMany("ExerciseMedia")
                        .HasForeignKey("MediaAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("MediaAsset");
                });

            modelBuilder.Entity("Data.Models.MediaAsset", b =>
                {
                    b.HasOne("Data.Models.Patient", "Patient")
                        .WithMany("MediaAssets")
                        .HasForeignKey("PatientId");

                    b.HasOne("Data.Identity.User", "UploadedBy")
                        .WithMany("MediaAssets")
                        .HasForeignKey("UploadedByUserId");

                    b.Navigation("Patient");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("Data.Models.Patient", b =>
                {
                    b.HasOne("Data.Identity.User", "User")
                        .WithMany("ManagedPatients")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Data.Models.PatientAssignment", b =>
                {
                    b.HasOne("Data.Models.Patient", "Patient")
                        .WithMany("Assignments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Identity.User", "Therapist")
                        .WithMany("AssignedPatients")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("Therapist");
                });

            modelBuilder.Entity("Data.Models.PatientCondition", b =>
                {
                    b.HasOne("Data.Models.Condition", "Condition")
                        .WithMany("PatientConditions")
                        .HasForeignKey("ConditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Identity.User", "CreatedBy")
                        .WithMany("PatientConditions")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.Patient", "Patient")
                        .WithMany("Conditions")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Condition");

                    b.Navigation("CreatedBy");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Data.Models.PatientStageStatus", b =>
                {
                    b.HasOne("Data.Identity.User", "ChangedBy")
                        .WithMany("PatientStageStatuses")
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.RehabStage", "CurrentStage")
                        .WithMany("PatientStatuses")
                        .HasForeignKey("CurrentStageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.PatientCondition", "PatientCondition")
                        .WithMany("StageStatuses")
                        .HasForeignKey("PatientConditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.RehabProtocol", "Protocol")
                        .WithMany("PatientStatuses")
                        .HasForeignKey("ProtocolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedBy");

                    b.Navigation("CurrentStage");

                    b.Navigation("PatientCondition");

                    b.Navigation("Protocol");
                });

            modelBuilder.Entity("Data.Models.ProgressEntry", b =>
                {
                    b.HasOne("Data.Identity.User", "CreatedBy")
                        .WithMany("ProgressEntries")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.Patient", "Patient")
                        .WithMany("ProgressEntries")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.WorkoutSession", "Session")
                        .WithMany("ProgressEntries")
                        .HasForeignKey("WorkoutSessionId");

                    b.Navigation("CreatedBy");

                    b.Navigation("Patient");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Data.Models.RehabProtocol", b =>
                {
                    b.HasOne("Data.Models.Condition", "Condition")
                        .WithMany("RehabProtocols")
                        .HasForeignKey("ConditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Identity.User", "Owner")
                        .WithMany("RehabProtocols")
                        .HasForeignKey("OwnerId");

                    b.Navigation("Condition");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Data.Models.RehabStage", b =>
                {
                    b.HasOne("Data.Models.RehabProtocol", "Protocol")
                        .WithMany("Stages")
                        .HasForeignKey("ProtocolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Protocol");
                });

            modelBuilder.Entity("Data.Models.StageCriterion", b =>
                {
                    b.HasOne("Data.Models.RehabStage", "Stage")
                        .WithMany("Criteria")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("Data.Models.Template", b =>
                {
                    b.HasOne("Data.Identity.User", "Owner")
                        .WithMany("Templates")
                        .HasForeignKey("OwnerId");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Data.Models.TemplateItem", b =>
                {
                    b.HasOne("Data.Models.Exercise", "Exercise")
                        .WithMany("TemplateItems")
                        .HasForeignKey("ExerciseId");

                    b.HasOne("Data.Models.Template", "Template")
                        .WithMany("Items")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Data.Models.TestDefinition", b =>
                {
                    b.HasOne("Data.Identity.User", "Owner")
                        .WithMany("TestDefinitions")
                        .HasForeignKey("OwnerId");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Data.Models.TestResult", b =>
                {
                    b.HasOne("Data.Identity.User", "CreatedBy")
                        .WithMany("TestResults")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.PatientCondition", "PatientCondition")
                        .WithMany("TestResults")
                        .HasForeignKey("PatientConditionId");

                    b.HasOne("Data.Models.Patient", "Patient")
                        .WithMany("TestResults")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.TestDefinition", "TestDefinition")
                        .WithMany("Results")
                        .HasForeignKey("TestDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.WorkoutSession", "Session")
                        .WithMany("TestResults")
                        .HasForeignKey("WorkoutSessionId");

                    b.Navigation("CreatedBy");

                    b.Navigation("Patient");

                    b.Navigation("PatientCondition");

                    b.Navigation("Session");

                    b.Navigation("TestDefinition");
                });

            modelBuilder.Entity("Data.Models.VisitNote", b =>
                {
                    b.HasOne("Data.Identity.User", "Author")
                        .WithMany("AuthoredVisitNotes")
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.Patient", "Patient")
                        .WithMany("VisitNotes")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Data.Models.WorkoutExercise", b =>
                {
                    b.HasOne("Data.Models.Exercise", "Exercise")
                        .WithMany("WorkoutExercises")
                        .HasForeignKey("ExerciseId");

                    b.HasOne("Data.Models.MediaAsset", "InstructionMedia")
                        .WithMany()
                        .HasForeignKey("InstructionMediaId");

                    b.HasOne("Data.Models.WorkoutSession", "Session")
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("InstructionMedia");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Data.Models.WorkoutPlan", b =>
                {
                    b.HasOne("Data.Identity.User", "CreatedBy")
                        .WithMany("WorkoutPlans")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.Patient", "Patient")
                        .WithMany("WorkoutPlans")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.Template", "SourceTemplate")
                        .WithMany("WorkoutPlans")
                        .HasForeignKey("SourceTemplateId");

                    b.Navigation("CreatedBy");

                    b.Navigation("Patient");

                    b.Navigation("SourceTemplate");
                });

            modelBuilder.Entity("Data.Models.WorkoutSession", b =>
                {
                    b.HasOne("Data.Models.Patient", "Patient")
                        .WithMany("WorkoutSessions")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data.Models.WorkoutPlan", "WorkoutPlan")
                        .WithMany("Sessions")
                        .HasForeignKey("WorkoutPlanId");

                    b.Navigation("Patient");

                    b.Navigation("WorkoutPlan");
                });

            modelBuilder.Entity("Data.Identity.User", b =>
                {
                    b.Navigation("AssignedPatients");

                    b.Navigation("AuthoredVisitNotes");

                    b.Navigation("ExerciseLogs");

                    b.Navigation("Exercises");

                    b.Navigation("ManagedPatients");

                    b.Navigation("MediaAssets");

                    b.Navigation("PatientConditions");

                    b.Navigation("PatientStageStatuses");

                    b.Navigation("ProgressEntries");

                    b.Navigation("RehabProtocols");

                    b.Navigation("Templates");

                    b.Navigation("TestDefinitions");

                    b.Navigation("TestResults");

                    b.Navigation("WorkoutPlans");
                });

            modelBuilder.Entity("Data.Models.Condition", b =>
                {
                    b.Navigation("PatientConditions");

                    b.Navigation("RehabProtocols");

                    b.Navigation("TestRecommendations");
                });

            modelBuilder.Entity("Data.Models.Exercise", b =>
                {
                    b.Navigation("ExerciseMedia");

                    b.Navigation("TemplateItems");

                    b.Navigation("WorkoutExercises");
                });

            modelBuilder.Entity("Data.Models.ExerciseLog", b =>
                {
                    b.Navigation("Media");
                });

            modelBuilder.Entity("Data.Models.MediaAsset", b =>
                {
                    b.Navigation("ExerciseLogMedia");

                    b.Navigation("ExerciseMedia");
                });

            modelBuilder.Entity("Data.Models.Patient", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Conditions");

                    b.Navigation("ExerciseLogs");

                    b.Navigation("MediaAssets");

                    b.Navigation("ProgressEntries");

                    b.Navigation("TestResults");

                    b.Navigation("VisitNotes");

                    b.Navigation("WorkoutPlans");

                    b.Navigation("WorkoutSessions");
                });

            modelBuilder.Entity("Data.Models.PatientCondition", b =>
                {
                    b.Navigation("StageStatuses");

                    b.Navigation("TestResults");
                });

            modelBuilder.Entity("Data.Models.RehabProtocol", b =>
                {
                    b.Navigation("PatientStatuses");

                    b.Navigation("Stages");
                });

            modelBuilder.Entity("Data.Models.RehabStage", b =>
                {
                    b.Navigation("Criteria");

                    b.Navigation("PatientStatuses");
                });

            modelBuilder.Entity("Data.Models.Template", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("WorkoutPlans");
                });

            modelBuilder.Entity("Data.Models.TestDefinition", b =>
                {
                    b.Navigation("Recommendations");

                    b.Navigation("Results");
                });

            modelBuilder.Entity("Data.Models.WorkoutExercise", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("Data.Models.WorkoutPlan", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Data.Models.WorkoutSession", b =>
                {
                    b.Navigation("Exercises");

                    b.Navigation("ProgressEntries");

                    b.Navigation("TestResults");
                });
#pragma warning restore 612, 618
        }
    }
}
